// <auto-generated />
using EmployeeRegisterAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20240831151036_EmployeeDBContext")]
    partial class EmployeeDBContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-rc.1.23419.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeRegitsAPI.Models.Admin", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("username");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("EmployeeRegitsAPI.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeUsername")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeePassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EmployeeUsername");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeeRegitsAPI.Models.EmployeeData", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<long>("EmployeeAllowance")
                        .HasColumnType("bigint");

                    b.Property<string>("EmployeeGender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeNik")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeePassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EmployeeSalary")
                        .HasColumnType("bigint");

                    b.Property<string>("EmployeeStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employeed");
                });

            modelBuilder.Entity("EmployeeRegitsAPI.Models.TaxData", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<long>("EmployeeAllowance")
                        .HasColumnType("bigint");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeNik")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("EmployeeSalary")
                        .HasColumnType("bigint");

                    b.Property<long>("TaxAni")
                        .HasColumnType("bigint");

                    b.Property<long>("TaxJht")
                        .HasColumnType("bigint");

                    b.Property<long>("TaxJkk")
                        .HasColumnType("bigint");

                    b.Property<long>("TaxJkm")
                        .HasColumnType("bigint");

                    b.Property<long>("TaxJpk")
                        .HasColumnType("bigint");

                    b.Property<long>("TaxMni")
                        .HasColumnType("bigint");

                    b.Property<long>("TaxOwed")
                        .HasColumnType("bigint");

                    b.Property<long>("TaxPkp")
                        .HasColumnType("bigint");

                    b.Property<long>("TaxPositiom")
                        .HasColumnType("bigint");

                    b.Property<long>("TaxPph21Month")
                        .HasColumnType("bigint");

                    b.Property<long>("TaxPph21Year")
                        .HasColumnType("bigint");

                    b.Property<long>("TaxPtkp")
                        .HasColumnType("bigint");

                    b.HasKey("EmployeeId");

                    b.ToTable("TaxDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
